name: Nova

version: 1.2+5

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.22.1
  built_value: ^6.4.0
  built_collection: ^4.2.0
  intl: ^0.15.8
  http: ^0.12.0+2
  flutter_secure_storage: ^3.2.1+1
  bubble_tab_indicator: ^0.1.4
  image_picker: ^0.6.0+4
  web_socket_channel: ^1.0.13
  url_launcher: ^5.0.3
  firebase_messaging: ^5.0.2
  retry: ^3.0.0
  curl:

dev_dependencies:
  built_value_generator: ^6.4.0
  build_runner: ^1.3.1
  flutter_launcher_icons: ^0.7.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  fonts:
  - family: Ubuntu
    fonts:
      - asset: assets/fonts/Ubuntu-Light.ttf
        weight: 300
      - asset: assets/fonts/Ubuntu-Regular.ttf
        weight: 400
      - asset: assets/fonts/Ubuntu-Medium.ttf
        weight: 500
  - family: NovaIcons
    fonts:
      - asset: assets/fonts/NovaIcons.ttf
  assets:
    - assets/user.png
    - assets/project.png
    - assets/loading.png
